import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import WalletProvider from '../context/WalletProvider';
import './globals.css'
import "@rainbow-me/rainbowkit/styles.css";
import Navbar from '@/layout/navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WalletProvider>
          <Navbar />
          {children}
        </WalletProvider>
      </body>
    </html>
  )
}
